insert into public.default_categories (name, sort_order, include_in_spend)
values
  ('Travel & Visa', 1, true),
  ('Fitness & Wellness', 2, true),
  ('Healthcare, Pharmacy & Insurance', 3, true),
  ('Food & Dining', 4, true),
  ('Shopping - Apparel, Beauty & General Retail', 5, true),
  ('Jewelry', 6, true),
  ('Technology & Electronics', 7, true),
  ('Groceries & Household', 8, true),
  ('Entertainment & Subscriptions', 9, true),
  ('Gift Cards & Vouchers', 10, true),
  ('Auto & Transport', 11, true),
  ('Government, Taxes & Fees', 12, true),
  ('Unknown / Needs Review', 13, true),
  ('Kids, Baby & Toys', 14, true),
  ('Personal Care & Wellness', 15, true),
  ('Home & Utilities', 16, true),
  ('Wallet/Payment App & Misc', 17, true),
  ('Charity & Donations', 18, true),
  ('Online Shopping / Marketplace', 19, true),
  ('Fees & Charges', 20, true),
  ('Payments/Credits (not expense)', 21, false);

insert into public.default_subcategories (default_category_id, name, sort_order)
select dc.id, seed.name, seed.sort_order
from (
  values
    ('Travel & Visa', 'Flights', 1),
    ('Travel & Visa', 'Train tickets', 2),
    ('Travel & Visa', 'Visa services', 3),
    ('Travel & Visa', 'Travel booking', 4),
    ('Travel & Visa', 'Hotels', 5),
    ('Travel & Visa', 'Ride-hailing', 6),
    ('Travel & Visa', 'Lounge/reversal', 7),
    ('Fitness & Wellness', 'Gym/fitness', 1),
    ('Healthcare, Pharmacy & Insurance', 'Hospitals/clinics', 1),
    ('Healthcare, Pharmacy & Insurance', 'Pharmacy/healthcare', 2),
    ('Healthcare, Pharmacy & Insurance', 'Insurance', 3),
    ('Food & Dining', 'Food delivery', 1),
    ('Food & Dining', 'Restaurants/cafes', 2),
    ('Shopping - Apparel, Beauty & General Retail', 'Apparel/beauty/general retail', 1),
    ('Shopping - Apparel, Beauty & General Retail', 'Retail - needs review', 2),
    ('Jewelry', 'Jewelry/gold', 1),
    ('Technology & Electronics', 'Electronics/IT/cloud', 1),
    ('Groceries & Household', 'Grocery/quick commerce', 1),
    ('Entertainment & Subscriptions', 'Streaming/gaming/apps', 1),
    ('Entertainment & Subscriptions', 'Cinema', 2),
    ('Entertainment & Subscriptions', 'Cinema/events', 3),
    ('Gift Cards & Vouchers', 'Gift vouchers', 1),
    ('Auto & Transport', 'Auto service/accessories/Fastag', 1),
    ('Government, Taxes & Fees', 'Government payment', 1),
    ('Unknown / Needs Review', 'Merchant unclear', 1),
    ('Kids, Baby & Toys', 'Kids/baby/toys', 1),
    ('Personal Care & Wellness', 'Salon/spa/personal care', 1),
    ('Home & Utilities', 'Home services/water', 1),
    ('Home & Utilities', 'Telecom', 2),
    ('Wallet/Payment App & Misc', 'Payment app - unknown underlying spend', 1),
    ('Charity & Donations', 'Donation/crowdfunding', 1),
    ('Online Shopping / Marketplace', 'Marketplace purchase/refund', 1),
    ('Fees & Charges', 'FX/DCC/GST fees', 1),
    ('Payments/Credits (not expense)', 'Card bill payment', 1)
) as seed(category_name, name, sort_order)
join public.default_categories dc on dc.name = seed.category_name;
